---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: writerregistration
  labels:
    app: writerregistration
spec:
  replicas: 1
  selector:
    matchLabels:
      app: writerregistration
  template:
    metadata:
      labels:
        app: writerregistration
    spec:
      containers:
        - name: writerregistration
          image: username/writerregistration:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: subscriptionandpoint
  labels:
    app: subscriptionandpoint
spec:
  replicas: 1
  selector:
    matchLabels:
      app: subscriptionandpoint
  template:
    metadata:
      labels:
        app: subscriptionandpoint
    spec:
      containers:
        - name: subscriptionandpoint
          image: username/subscriptionandpoint:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookpublication
  labels:
    app: bookpublication
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookpublication
  template:
    metadata:
      labels:
        app: bookpublication
    spec:
      containers:
        - name: bookpublication
          image: username/bookpublication:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: aibookautomation
  labels:
    app: aibookautomation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aibookautomation
  template:
    metadata:
      labels:
        app: aibookautomation
    spec:
      containers:
        - name: aibookautomation
          image: username/aibookautomation:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5


---


apiVersion: v1
kind: Service
metadata:
  name: writerregistration
  labels:
    app: writerregistration
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: writerregistration


---


apiVersion: v1
kind: Service
metadata:
  name: subscriptionandpoint
  labels:
    app: subscriptionandpoint
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: subscriptionandpoint


---


apiVersion: v1
kind: Service
metadata:
  name: bookpublication
  labels:
    app: bookpublication
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: bookpublication


---


apiVersion: v1
kind: Service
metadata:
  name: aibookautomation
  labels:
    app: aibookautomation
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: aibookautomation

