apiVersion: v1
kind: Service
metadata:
  name: subscriptionandpoint
  labels:
    app: subscriptionandpoint
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: subscriptionandpoint